//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyU.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_install_rec {
            get {
                return ((string)(this["dev_install_rec"]));
            }
            set {
                this["dev_install_rec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_sel_firmware {
            get {
                return ((string)(this["dev_sel_firmware"]));
            }
            set {
                this["dev_sel_firmware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_self_host {
            get {
                return ((string)(this["dev_self_host"]));
            }
            set {
                this["dev_self_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_target {
            get {
                return ((string)(this["dev_target"]));
            }
            set {
                this["dev_target"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ddd {
            get {
                return ((string)(this["inst_ddd"]));
            }
            set {
                this["inst_ddd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_sd_caffiine {
            get {
                return ((string)(this["inst_sd_caffiine"]));
            }
            set {
                this["inst_sd_caffiine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_sav {
            get {
                return ((string)(this["inst_sav"]));
            }
            set {
                this["inst_sav"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_pong {
            get {
                return ((string)(this["inst_pong"]));
            }
            set {
                this["inst_pong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_gac {
            get {
                return ((string)(this["inst_gac"]));
            }
            set {
                this["inst_gac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_tic {
            get {
                return ((string)(this["inst_tic"]));
            }
            set {
                this["inst_tic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_pac {
            get {
                return ((string)(this["inst_pac"]));
            }
            set {
                this["inst_pac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_u_paint {
            get {
                return ((string)(this["inst_u_paint"]));
            }
            set {
                this["inst_u_paint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ftp {
            get {
                return ((string)(this["inst_ftp"]));
            }
            set {
                this["inst_ftp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ast {
            get {
                return ((string)(this["inst_ast"]));
            }
            set {
                this["inst_ast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_nnu {
            get {
                return ((string)(this["inst_nnu"]));
            }
            set {
                this["inst_nnu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_geck {
            get {
                return ((string)(this["inst_geck"]));
            }
            set {
                this["inst_geck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_gbiine {
            get {
                return ((string)(this["inst_gbiine"]));
            }
            set {
                this["inst_gbiine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_tcp {
            get {
                return ((string)(this["inst_tcp"]));
            }
            set {
                this["inst_tcp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_hid {
            get {
                return ((string)(this["inst_hid"]));
            }
            set {
                this["inst_hid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_snake {
            get {
                return ((string)(this["inst_snake"]));
            }
            set {
                this["inst_snake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_cave {
            get {
                return ((string)(this["inst_cave"]));
            }
            set {
                this["inst_cave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_chip {
            get {
                return ((string)(this["inst_chip"]));
            }
            set {
                this["inst_chip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_wiiu_key {
            get {
                return ((string)(this["inst_wiiu_key"]));
            }
            set {
                this["inst_wiiu_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_wup {
            get {
                return ((string)(this["inst_wup"]));
            }
            set {
                this["inst_wup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sd_form {
            get {
                return ((string)(this["sd_form"]));
            }
            set {
                this["sd_form"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sd_form_drive {
            get {
                return ((string)(this["sd_form_drive"]));
            }
            set {
                this["sd_form_drive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sd_form_cluster {
            get {
                return ((string)(this["sd_form_cluster"]));
            }
            set {
                this["sd_form_cluster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_upd {
            get {
                return ((string)(this["dev_upd"]));
            }
            set {
                this["dev_upd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_grab_night {
            get {
                return ((string)(this["dev_grab_night"]));
            }
            set {
                this["dev_grab_night"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_cleanup {
            get {
                return ((string)(this["dev_cleanup"]));
            }
            set {
                this["dev_cleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_dev_mode {
            get {
                return ((string)(this["dev_dev_mode"]));
            }
            set {
                this["dev_dev_mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_space {
            get {
                return ((string)(this["inst_space"]));
            }
            set {
                this["inst_space"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_our {
            get {
                return ((string)(this["inst_our"]));
            }
            set {
                this["inst_our"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_app_dark {
            get {
                return ((string)(this["inst_app_dark"]));
            }
            set {
                this["inst_app_dark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_poke {
            get {
                return ((string)(this["inst_poke"]));
            }
            set {
                this["inst_poke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_hid_key {
            get {
                return ((string)(this["inst_hid_key"]));
            }
            set {
                this["inst_hid_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_live {
            get {
                return ((string)(this["inst_live"]));
            }
            set {
                this["inst_live"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_synth {
            get {
                return ((string)(this["inst_synth"]));
            }
            set {
                this["inst_synth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ios {
            get {
                return ((string)(this["inst_ios"]));
            }
            set {
                this["inst_ios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_flappy {
            get {
                return ((string)(this["inst_flappy"]));
            }
            set {
                this["inst_flappy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_bck_music {
            get {
                return ((string)(this["dev_bck_music"]));
            }
            set {
                this["dev_bck_music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_log_dump {
            get {
                return ((string)(this["dev_log_dump"]));
            }
            set {
                this["dev_log_dump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_log_state {
            get {
                return ((string)(this["dev_log_state"]));
            }
            set {
                this["dev_log_state"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_bck_music_en {
            get {
                return ((string)(this["dev_bck_music_en"]));
            }
            set {
                this["dev_bck_music_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string terms_agreed {
            get {
                return ((string)(this["terms_agreed"]));
            }
            set {
                this["terms_agreed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_guide {
            get {
                return ((string)(this["dev_guide"]));
            }
            set {
                this["dev_guide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_rednand {
            get {
                return ((string)(this["dev_rednand"]));
            }
            set {
                this["dev_rednand"] = value;
            }
        }
        
        /// <summary>
        /// This is the String for the Theme Setting
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("This is the String for the Theme Setting")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string dev_theme {
            get {
                return ((string)(this["dev_theme"]));
            }
            set {
                this["dev_theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_rednand_sd {
            get {
                return ((string)(this["dev_rednand_sd"]));
            }
            set {
                this["dev_rednand_sd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_rednand_sys {
            get {
                return ((string)(this["dev_rednand_sys"]));
            }
            set {
                this["dev_rednand_sys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_rednand_fw {
            get {
                return ((string)(this["dev_rednand_fw"]));
            }
            set {
                this["dev_rednand_fw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_hbl {
            get {
                return ((string)(this["inst_hbl"]));
            }
            set {
                this["inst_hbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_hbl_dark {
            get {
                return ((string)(this["inst_hbl_dark"]));
            }
            set {
                this["inst_hbl_dark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_retro {
            get {
                return ((string)(this["inst_retro"]));
            }
            set {
                this["inst_retro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_loadiine {
            get {
                return ((string)(this["inst_loadiine"]));
            }
            set {
                this["inst_loadiine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_loadiine_y {
            get {
                return ((string)(this["inst_loadiine_y"]));
            }
            set {
                this["inst_loadiine_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ft2sd {
            get {
                return ((string)(this["inst_ft2sd"]));
            }
            set {
                this["inst_ft2sd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_ftpiu_every {
            get {
                return ((string)(this["inst_ftpiu_every"]));
            }
            set {
                this["inst_ftpiu_every"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_wudumper {
            get {
                return ((string)(this["inst_wudumper"]));
            }
            set {
                this["inst_wudumper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_seeprom {
            get {
                return ((string)(this["inst_seeprom"]));
            }
            set {
                this["inst_seeprom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_sigpat_hbl {
            get {
                return ((string)(this["inst_sigpat_hbl"]));
            }
            set {
                this["inst_sigpat_hbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_wuphax {
            get {
                return ((string)(this["inst_wuphax"]));
            }
            set {
                this["inst_wuphax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_otp2sd {
            get {
                return ((string)(this["inst_otp2sd"]));
            }
            set {
                this["inst_otp2sd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_padcon {
            get {
                return ((string)(this["inst_padcon"]));
            }
            set {
                this["inst_padcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_tik2sd {
            get {
                return ((string)(this["inst_tik2sd"]));
            }
            set {
                this["inst_tik2sd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fsdumper {
            get {
                return ((string)(this["inst_fsdumper"]));
            }
            set {
                this["inst_fsdumper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_cbhc {
            get {
                return ((string)(this["inst_cbhc"]));
            }
            set {
                this["inst_cbhc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_haxchi {
            get {
                return ((string)(this["inst_haxchi"]));
            }
            set {
                this["inst_haxchi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_aoc {
            get {
                return ((string)(this["inst_aoc"]));
            }
            set {
                this["inst_aoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_sigpat_sysmenu {
            get {
                return ((string)(this["inst_sigpat_sysmenu"]));
            }
            set {
                this["inst_sigpat_sysmenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fuse {
            get {
                return ((string)(this["inst_fuse"]));
            }
            set {
                this["inst_fuse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fceumm {
            get {
                return ((string)(this["inst_fceumm"]));
            }
            set {
                this["inst_fceumm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_mame2003 {
            get {
                return ((string)(this["inst_mame2003"]));
            }
            set {
                this["inst_mame2003"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_quicknes {
            get {
                return ((string)(this["inst_quicknes"]));
            }
            set {
                this["inst_quicknes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_psx {
            get {
                return ((string)(this["inst_psx"]));
            }
            set {
                this["inst_psx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_beetlevb {
            get {
                return ((string)(this["inst_beetlevb"]));
            }
            set {
                this["inst_beetlevb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_genisis {
            get {
                return ((string)(this["inst_genisis"]));
            }
            set {
                this["inst_genisis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_mame {
            get {
                return ((string)(this["inst_mame"]));
            }
            set {
                this["inst_mame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_nestopia {
            get {
                return ((string)(this["inst_nestopia"]));
            }
            set {
                this["inst_nestopia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_snes9x {
            get {
                return ((string)(this["inst_snes9x"]));
            }
            set {
                this["inst_snes9x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fb_cps2 {
            get {
                return ((string)(this["inst_fb_cps2"]));
            }
            set {
                this["inst_fb_cps2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_beetle_sgx {
            get {
                return ((string)(this["inst_beetle_sgx"]));
            }
            set {
                this["inst_beetle_sgx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_beetle_neo {
            get {
                return ((string)(this["inst_beetle_neo"]));
            }
            set {
                this["inst_beetle_neo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_nxe {
            get {
                return ((string)(this["inst_nxe"]));
            }
            set {
                this["inst_nxe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fb_cps3 {
            get {
                return ((string)(this["inst_fb_cps3"]));
            }
            set {
                this["inst_fb_cps3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_snes9x_2010 {
            get {
                return ((string)(this["inst_snes9x_2010"]));
            }
            set {
                this["inst_snes9x_2010"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_lynx {
            get {
                return ((string)(this["inst_lynx"]));
            }
            set {
                this["inst_lynx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_prboom {
            get {
                return ((string)(this["inst_prboom"]));
            }
            set {
                this["inst_prboom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fb_cps1 {
            get {
                return ((string)(this["inst_fb_cps1"]));
            }
            set {
                this["inst_fb_cps1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_gamebatte {
            get {
                return ((string)(this["inst_gamebatte"]));
            }
            set {
                this["inst_gamebatte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fba {
            get {
                return ((string)(this["inst_fba"]));
            }
            set {
                this["inst_fba"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_beetle_pcef {
            get {
                return ((string)(this["inst_beetle_pcef"]));
            }
            set {
                this["inst_beetle_pcef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_fb_neo {
            get {
                return ((string)(this["inst_fb_neo"]));
            }
            set {
                this["inst_fb_neo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_tyrquake {
            get {
                return ((string)(this["inst_tyrquake"]));
            }
            set {
                this["inst_tyrquake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string inst_beetle {
            get {
                return ((string)(this["inst_beetle"]));
            }
            set {
                this["inst_beetle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_fallbck {
            get {
                return ((string)(this["dev_fallbck"]));
            }
            set {
                this["dev_fallbck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Defualt")]
        public string dev_theme_prev {
            get {
                return ((string)(this["dev_theme_prev"]));
            }
            set {
                this["dev_theme_prev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dev_close_now {
            get {
                return ((string)(this["dev_close_now"]));
            }
            set {
                this["dev_close_now"] = value;
            }
        }
    }
}
